/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardYoutubeRouteImport } from './routes/dashboard.youtube'
import { Route as DashboardTiktokRouteImport } from './routes/dashboard.tiktok'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSchedulerRouteImport } from './routes/dashboard.scheduler'
import { Route as DashboardInstagramRouteImport } from './routes/dashboard.instagram'
import { Route as DashboardAiRouteImport } from './routes/dashboard.ai'
import { Route as DashboardAccountsRouteImport } from './routes/dashboard.accounts'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardYoutubeRoute = DashboardYoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTiktokRoute = DashboardTiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchedulerRoute = DashboardSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInstagramRoute = DashboardInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountsRoute = DashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/instagram': typeof DashboardInstagramRoute
  '/dashboard/scheduler': typeof DashboardSchedulerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tiktok': typeof DashboardTiktokRoute
  '/dashboard/youtube': typeof DashboardYoutubeRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/instagram': typeof DashboardInstagramRoute
  '/dashboard/scheduler': typeof DashboardSchedulerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tiktok': typeof DashboardTiktokRoute
  '/dashboard/youtube': typeof DashboardYoutubeRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/instagram': typeof DashboardInstagramRoute
  '/dashboard/scheduler': typeof DashboardSchedulerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tiktok': typeof DashboardTiktokRoute
  '/dashboard/youtube': typeof DashboardYoutubeRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/accounts'
    | '/dashboard/ai'
    | '/dashboard/instagram'
    | '/dashboard/scheduler'
    | '/dashboard/settings'
    | '/dashboard/tiktok'
    | '/dashboard/youtube'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/accounts'
    | '/dashboard/ai'
    | '/dashboard/instagram'
    | '/dashboard/scheduler'
    | '/dashboard/settings'
    | '/dashboard/tiktok'
    | '/dashboard/youtube'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/accounts'
    | '/dashboard/ai'
    | '/dashboard/instagram'
    | '/dashboard/scheduler'
    | '/dashboard/settings'
    | '/dashboard/tiktok'
    | '/dashboard/youtube'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/youtube': {
      id: '/dashboard/youtube'
      path: '/youtube'
      fullPath: '/dashboard/youtube'
      preLoaderRoute: typeof DashboardYoutubeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tiktok': {
      id: '/dashboard/tiktok'
      path: '/tiktok'
      fullPath: '/dashboard/tiktok'
      preLoaderRoute: typeof DashboardTiktokRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scheduler': {
      id: '/dashboard/scheduler'
      path: '/scheduler'
      fullPath: '/dashboard/scheduler'
      preLoaderRoute: typeof DashboardSchedulerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/instagram': {
      id: '/dashboard/instagram'
      path: '/instagram'
      fullPath: '/dashboard/instagram'
      preLoaderRoute: typeof DashboardInstagramRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounts': {
      id: '/dashboard/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardAccountsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountsRoute: typeof DashboardAccountsRoute
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardInstagramRoute: typeof DashboardInstagramRoute
  DashboardSchedulerRoute: typeof DashboardSchedulerRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTiktokRoute: typeof DashboardTiktokRoute
  DashboardYoutubeRoute: typeof DashboardYoutubeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountsRoute: DashboardAccountsRoute,
  DashboardAiRoute: DashboardAiRoute,
  DashboardInstagramRoute: DashboardInstagramRoute,
  DashboardSchedulerRoute: DashboardSchedulerRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTiktokRoute: DashboardTiktokRoute,
  DashboardYoutubeRoute: DashboardYoutubeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
